export const licenseCategories = [
  {
    name: 'applications services provider',
    licenses: [
      {
        id: 1,
        name: 'data center: tier one and two',
        application_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        renewal_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        first_time_application_fee: '100 USD',
        renewal_application_fee: '100 USD',
        first_time_license_fee: '100 USD',
        renewal_license_fee: '100 USD',
        validity: '15',
        processing_time: '30',
      },
      {
        id: 2,
        name: 'Data Center: tier 3 and above ',
        application_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        renewal_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        first_time_application_fee: '100 USD',
        renewal_application_fee: '100 USD',
        first_time_license_fee: '100 USD',
        renewal_license_fee: '100 USD',
        validity: '15',
        processing_time: '30',
      },
      {
        id: 3,
        name: 'E-services (e-ticketing, e-commerce platform, VAS, …)',
        application_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        renewal_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        first_time_application_fee: '100 USD',
        renewal_application_fee: '100 USD',
        first_time_license_fee: '100 USD',
        renewal_license_fee: '100 USD',
        validity: '15',
        processing_time: '30',
      },
      {
        id: 4,
        name: 'Retail ISP, VoIP, pay phone, tracking systems',
        application_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        renewal_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        first_time_application_fee: '100 USD',
        renewal_application_fee: '100 USD',
        first_time_license_fee: '100 USD',
        renewal_license_fee: '100 USD',
        validity: '15',
        processing_time: '30',
      },
      {
        id: 5,
        name: 'VPN approval certificate',
        application_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        renewal_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        first_time_application_fee: '100 USD',
        renewal_application_fee: '100 USD',
        first_time_license_fee: '100 USD',
        renewal_license_fee: '100 USD',
        validity: '15',
        processing_time: '30',
      },
    ]
  },
  {
    name: 'Network infrastructure',
    licenses: [
      {
        id: 6,
        name: 'international gateway system license ',
        application_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        renewal_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        first_time_application_fee: '100 USD',
        renewal_application_fee: '100 USD',
        first_time_license_fee: '100 USD',
        renewal_license_fee: '100 USD',
        validity: '15',
        processing_time: '30',
      }
    ]
  },
  {
    name: 'Network service provider',
    licenses: [
      {
        id: 7,
        name: 'network service provider license tier 1',
        application_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        renewal_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        first_time_application_fee: '100 USD',
        renewal_application_fee: '100 USD',
        first_time_license_fee: '100 USD',
        renewal_license_fee: '100 USD',
        validity: '15',
        processing_time: '30',
      },
      {
        id: 8,
        name: 'Radio communications license for ISP tier two',
        application_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        renewal_requirements: [
          'A copy of certificate of company registration including Information on the shareholding structure',
          'ID or passport of the legal representative of the company',
          'A detailed Business Plan (see the attached)',
          'Agreement between Telecoms, Banks, Digital Financial Services, and ATM services providers if any.',
          'Documentation that demonstrates that the applicant has the technical experience and capability to manage the system',
          'Technical Specifications, details (see the attached template on technical specifications)',
        ],
        first_time_application_fee: '100 USD',
        renewal_application_fee: '100 USD',
        first_time_license_fee: '100 USD',
        renewal_license_fee: '100 USD',
        validity: '15',
        processing_time: '30',
      },
    ]
  },
]